

MYSQL_USER = "root"
MYSQL_PASSWORD = "Rupali09"
MYSQL_HOST = "localhost"
MYSQL_DB = "medical_lab_db"

SQLALCHEMY_DATABASE_URI = (
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DB}"
)
SQLALCHEMY_TRACK_MODIFICATIONS = False
